# Generated by Django 4.1.7 on 2023-03-05 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_id_teachbase', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('role_id', models.IntegerField(default=1)),
                ('auth_type', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('lang', models.CharField(default='ru', max_length=30)),
            ],
        ),
    ]
