# Generated by Django 4.1.7 on 2023-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id_teachbase',
            field=models.IntegerField(default=0),
        ),
    ]
